import type { SandboxSession } from "@/lib/agent/sandbox/e2b";
import {
	formatCodeExecutionError,
	formatSandboxOperationError,
} from "@/lib/agent/utils/error-utils";
import { tool, zodSchema } from "ai";
import { z } from "zod";

type CodeInterpreterOptions = {
	fileIds?: string[];
	sandboxSession: SandboxSession;
};

const createCodeInterpreterTool = ({
	fileIds = [],
	sandboxSession,
}: CodeInterpreterOptions) =>
	tool({
		description:
			"Execute Python code in an isolated Jupyter notebook sandbox. Use for data analysis, calculations, chart generation, and any Python computation. Each call runs in a notebook cell, so variables persist between calls.",
		inputSchema: zodSchema(
			z.object({
				code: z.string().describe("Python code to execute in a notebook cell"),
			}),
		),
		execute: async ({ code }: { code: string }) => {
			let result: Awaited<ReturnType<SandboxSession["executeCode"]>>;
			try {
				result = await sandboxSession.executeCode(code, fileIds);
			} catch (error) {
				throw new Error(
					formatSandboxOperationError("codeInterpreter.execute", error),
				);
			}

			if (result.error) {
				throw new Error(
					formatCodeExecutionError({
						error: result.error,
						stderr: result.stderr,
						stdout: result.stdout,
					}),
				);
			}

			return {
				status: "success" as const,
				text: result.text,
				results: result.results,
				stdout: result.stdout,
				stderr: result.stderr,
			};
		},
	});

const createPersistCodeFileTool = (sandboxSession: SandboxSession) =>
	tool({
		description:
			"Persist a file generated inside the code interpreter sandbox to storage. Use this after creating a cleaned CSV or another analysis output file.",
		inputSchema: zodSchema(
			z.object({
				contentType: z
					.string()
					.optional()
					.describe("MIME type of the exported file"),
				filename: z
					.string()
					.optional()
					.describe("Optional output filename shown to the user"),
				filePath: z
					.string()
					.describe("Absolute file path inside the code interpreter sandbox"),
				kind: z
					.enum(["dataset", "document"])
					.optional()
					.describe("Semantic kind of the exported file"),
			}),
		),
		execute: async ({
			contentType,
			filename,
			filePath,
			kind,
		}: {
			contentType?: string;
			filename?: string;
			filePath: string;
			kind?: "dataset" | "document";
		}) => {
			const record = await sandboxSession.persistCodeFile({
				contentType,
				filename,
				filePath,
				kind,
			});

			return {
				contentType: record.contentType,
				downloadUrl: `/api/file/${record.id}/download`,
				fileId: record.id,
				filename: record.filename,
				kind: record.kind,
				preview: record.preview,
				status: "success" as const,
			};
		},
	});

const createPersistLatestChartTool = (sandboxSession: SandboxSession) =>
	tool({
		description:
			"Persist the latest chart image generated by the code interpreter to storage.",
		inputSchema: zodSchema(
			z.object({
				contentType: z
					.string()
					.optional()
					.describe("MIME type of the chart file"),
				filename: z
					.string()
					.optional()
					.describe("Optional output filename shown to the user"),
			}),
		),
		execute: async ({
			contentType,
			filename,
		}: {
			contentType?: string;
			filename?: string;
		}) => {
			const record = await sandboxSession.persistLatestChart({
				contentType,
				filename,
			});

			return {
				contentType: record.contentType,
				downloadUrl: `/api/file/${record.id}/download`,
				fileId: record.id,
				filename: record.filename,
				status: "success" as const,
			};
		},
	});

export {
	createCodeInterpreterTool,
	createPersistCodeFileTool,
	createPersistLatestChartTool,
};
