import { executeCode } from "@/lib/e2b";
import { tool, zodSchema } from "ai";
import { z } from "zod";

type CodeInterpreterOptions = {
	fileIds?: string[];
};

const createCodeInterpreterTool = ({
	fileIds = [],
}: CodeInterpreterOptions = {}) =>
	tool({
		description:
			"Execute Python code in an isolated Jupyter notebook sandbox. Use for data analysis, calculations, chart generation, and any Python computation. Each call runs in a notebook cell, so variables persist between calls.",
		inputSchema: zodSchema(
			z.object({
				code: z.string().describe("Python code to execute in a notebook cell"),
			}),
		),
		execute: async ({ code }: { code: string }) => {
			try {
				const result = await executeCode(code, undefined, fileIds);

				return {
					status: result.error ? "error" : "success",
					text: result.text,
					results: result.results,
					stdout: result.stdout,
					stderr: result.stderr,
					error: result.error,
				};
			} catch (error) {
				return {
					status: "error",
					message:
						error instanceof Error ? error.message : "Code execution failed",
				};
			}
		},
	});

const createPersistCodeFileTool = () =>
	tool({
		description:
			"Persist a file generated inside the code interpreter sandbox to storage. Use this after creating a cleaned CSV or another analysis output file.",
		inputSchema: zodSchema(
			z.object({
				contentType: z
					.string()
					.optional()
					.describe("MIME type of the exported file"),
				filename: z
					.string()
					.optional()
					.describe("Optional output filename shown to the user"),
				filePath: z
					.string()
					.describe("Absolute file path inside the code interpreter sandbox"),
				kind: z
					.enum(["dataset", "document"])
					.optional()
					.describe("Semantic kind of the exported file"),
			}),
		),
		execute: async ({
			contentType,
			filename,
			filePath,
			kind,
		}: {
			contentType?: string;
			filename?: string;
			filePath: string;
			kind?: "dataset" | "document";
		}) => {
			try {
				const { persistCodeFile } = await import("@/lib/e2b");
				const record = await persistCodeFile({
					contentType,
					filename,
					filePath,
					kind,
				});

				return {
					contentType: record.contentType,
					downloadUrl: `/api/file/${record.id}/download`,
					fileId: record.id,
					filename: record.filename,
					kind: record.kind,
					preview: record.preview,
					status: "success",
				};
			} catch (error) {
				return {
					status: "error",
					message:
						error instanceof Error ? error.message : "Failed to persist file",
				};
			}
		},
	});

const createPersistLatestChartTool = () =>
	tool({
		description:
			"Persist the latest chart image generated by the code interpreter to storage.",
		inputSchema: zodSchema(
			z.object({
				contentType: z
					.string()
					.optional()
					.describe("MIME type of the chart file"),
				filename: z
					.string()
					.optional()
					.describe("Optional output filename shown to the user"),
			}),
		),
		execute: async ({
			contentType,
			filename,
		}: {
			contentType?: string;
			filename?: string;
		}) => {
			try {
				const { persistLatestChart } = await import("@/lib/e2b");
				const record = await persistLatestChart({
					contentType,
					filename,
				});

				return {
					contentType: record.contentType,
					downloadUrl: `/api/file/${record.id}/download`,
					fileId: record.id,
					filename: record.filename,
					status: "success",
				};
			} catch (error) {
				return {
					status: "error",
					message:
						error instanceof Error ? error.message : "Failed to persist chart",
				};
			}
		},
	});

export {
	createCodeInterpreterTool,
	createPersistCodeFileTool,
	createPersistLatestChartTool,
};
