import { findSkill, getSkills } from "@/lib/agent/skills";
import {
	createDesktopSandbox,
	executeCode,
	executeCommand,
	navigateBrowser,
	persistCodeFile,
	persistLatestChart,
	searchWeb,
} from "@/lib/e2b";
import { tool, zodSchema } from "ai";
import { z } from "zod";

type CreateChatToolsOptions = {
	fileIds?: string[];
};

const createSandboxTool = tool({
	description:
		"Create an E2B Desktop Sandbox with a full Ubuntu desktop and browser. Returns a VNC URL for viewing the remote desktop. Use this when the user needs browser automation or visual desktop interaction.",
	inputSchema: zodSchema(
		z.object({
			task: z
				.string()
				.describe("Description of what the agent needs to do in the sandbox"),
		}),
	),
	execute: async ({ task }: { task: string }) => {
		try {
			const { sandboxId, vncUrl } = await createDesktopSandbox();

			return {
				sandboxId,
				vncUrl,
				status: "running",
				message: `Sandbox created for task: ${task}`,
			};
		} catch (error) {
			return {
				status: "error",
				message:
					error instanceof Error ? error.message : "Failed to create sandbox",
			};
		}
	},
});

const executeShellTool = tool({
	description:
		"Execute a shell command in the desktop sandbox. IMPORTANT: You MUST call createSandbox before using this tool, otherwise it will fail.",
	inputSchema: zodSchema(
		z.object({
			command: z.string().describe("Shell command to execute in the sandbox"),
		}),
	),
	execute: async ({ command }: { command: string }) => {
		try {
			const result = await executeCommand(command);

			return {
				status: "success",
				stdout: result.stdout,
				stderr: result.stderr,
				exitCode: result.exitCode,
			};
		} catch (error) {
			return {
				status: "error",
				message:
					error instanceof Error ? error.message : "Command execution failed",
			};
		}
	},
});

const navigateBrowserTool = tool({
	description:
		"Open a URL in the desktop sandbox browser. IMPORTANT: You MUST call createSandbox before using this tool, otherwise it will fail.",
	inputSchema: zodSchema(
		z.object({
			url: z.string().describe("URL to navigate to"),
		}),
	),
	execute: async ({ url }: { url: string }) => {
		try {
			const result = await navigateBrowser(url);

			return {
				status: "success",
				url: result.url,
				message: result.title,
			};
		} catch (error) {
			return {
				status: "error",
				message: error instanceof Error ? error.message : "Navigation failed",
			};
		}
	},
});

const searchWebTool = tool({
	description:
		"Search the web by opening Google in the desktop sandbox browser. IMPORTANT: You MUST call createSandbox before using this tool, otherwise it will fail.",
	inputSchema: zodSchema(
		z.object({
			query: z.string().describe("Search query"),
		}),
	),
	execute: async ({ query }: { query: string }) => {
		try {
			const result = await searchWeb(query);

			return {
				status: "success",
				query: result.query,
				results: result.results,
			};
		} catch (error) {
			return {
				status: "error",
				message: error instanceof Error ? error.message : "Search failed",
			};
		}
	},
});

const persistCodeFileTool = tool({
	description:
		"Persist a file generated inside the code interpreter sandbox to storage. Use this after creating a cleaned CSV or another analysis output file. Returns a downloadable file reference and dataset preview when applicable.",
	inputSchema: zodSchema(
		z.object({
			contentType: z
				.string()
				.optional()
				.describe("MIME type of the exported file"),
			filename: z
				.string()
				.optional()
				.describe("Optional output filename shown to the user"),
			filePath: z
				.string()
				.describe("Absolute file path inside the code interpreter sandbox"),
			kind: z
				.enum(["dataset", "document"])
				.optional()
				.describe("Semantic kind of the exported file"),
		}),
	),
	execute: async ({
		contentType,
		filename,
		filePath,
		kind,
	}: {
		contentType?: string;
		filename?: string;
		filePath: string;
		kind?: "dataset" | "document";
	}) => {
		try {
			const record = await persistCodeFile({
				contentType,
				filename,
				filePath,
				kind,
			});

			return {
				contentType: record.contentType,
				downloadUrl: `/api/file/${record.id}/download`,
				fileId: record.id,
				filename: record.filename,
				kind: record.kind,
				preview: record.preview,
				status: "success",
			};
		} catch (error) {
			return {
				status: "error",
				message:
					error instanceof Error ? error.message : "Failed to persist file",
			};
		}
	},
});

const persistLatestChartTool = tool({
	description:
		"Persist the latest chart image generated by the code interpreter to storage. Use this when the user wants to keep or download the chart artifact after analysis.",
	inputSchema: zodSchema(
		z.object({
			contentType: z
				.string()
				.optional()
				.describe("MIME type of the chart file"),
			filename: z
				.string()
				.optional()
				.describe("Optional output filename shown to the user"),
		}),
	),
	execute: async ({
		contentType,
		filename,
	}: {
		contentType?: string;
		filename?: string;
	}) => {
		try {
			const record = await persistLatestChart({
				contentType,
				filename,
			});

			return {
				contentType: record.contentType,
				downloadUrl: `/api/file/${record.id}/download`,
				fileId: record.id,
				filename: record.filename,
				status: "success",
			};
		} catch (error) {
			return {
				status: "error",
				message:
					error instanceof Error ? error.message : "Failed to persist chart",
			};
		}
	},
});

const createCodeInterpreterTool = ({
	fileIds = [],
}: CreateChatToolsOptions = {}) =>
	tool({
		description:
			"Execute Python code in an isolated Jupyter notebook sandbox. Use for data analysis, calculations, chart generation, and any Python computation. Each call runs in a notebook cell, so variables persist between calls.",
		inputSchema: zodSchema(
			z.object({
				code: z.string().describe("Python code to execute in a notebook cell"),
			}),
		),
		execute: async ({ code }: { code: string }) => {
			try {
				const result = await executeCode(code, undefined, fileIds);

				return {
					status: result.error ? "error" : "success",
					text: result.text,
					results: result.results,
					stdout: result.stdout,
					stderr: result.stderr,
					error: result.error,
				};
			} catch (error) {
				return {
					status: "error",
					message:
						error instanceof Error ? error.message : "Code execution failed",
				};
			}
		},
	});

const loadSkillTool = tool({
	description:
		"Load the full content of a skill into the agent's context. Use this when you need detailed information about how to handle a specific type of request (e.g., creating a paper, resume, or notes with Typst). This will provide you with comprehensive instructions, templates, and guidelines for the skill area.",
	inputSchema: zodSchema(
		z.object({
			skill_name: z.string().describe("The name of the skill to load"),
		}),
	),
	execute: async ({ skill_name }: { skill_name: string }) => {
		const skill = findSkill(skill_name);
		if (skill) {
			return `Loaded skill: ${skill.name}\n\n${skill.content}`;
		}
		const available = getSkills()
			.map((s) => s.name)
			.join(", ");
		return `Skill '${skill_name}' not found. Available skills: ${available}`;
	},
});

const createChatTools = ({ fileIds = [] }: CreateChatToolsOptions = {}) => ({
	createSandbox: createSandboxTool,
	codeInterpreter: createCodeInterpreterTool({ fileIds }),
	executeShell: executeShellTool,
	loadSkill: loadSkillTool,
	navigateBrowser: navigateBrowserTool,
	persistCodeFile: persistCodeFileTool,
	persistLatestChart: persistLatestChartTool,
	searchWeb: searchWebTool,
});

export {
	createChatTools,
	createCodeInterpreterTool,
	createSandboxTool,
	executeShellTool,
	loadSkillTool,
	navigateBrowserTool,
	persistCodeFileTool,
	persistLatestChartTool,
	searchWebTool,
};
